# Generated by Cursor on 2026-03-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="share_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tweet",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="feed.tweet"),
                ),
            ],
        ),
    ]

